# Generated by Django 2.1.4 on 2019-01-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=45)),
                ('firstName', models.CharField(max_length=45)),
                ('nationality', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=145)),
                ('type', models.CharField(choices=[('pdf', 'pdf'), ('epub', 'epub'), ('mobi', 'mobi'), ('doc', 'doc'), ('html', 'html'), ('other', 'other')], default='pdf', max_length=5)),
                ('location', models.CharField(max_length=128)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartile.Author')),
            ],
        ),
    ]
